export type FacultyMember = {
  name: string;
  departments: string[];
};

export const CALPOLY_FACULTY: FacultyMember[] = [
  { name: "Dongfeng Fang", departments: ["Computer Science", "Computer Engineering"] },
  { name: "Siavash Farzan", departments: ["Electrical Engineering"] },
  { name: "Francisco Fernflores", departments: ["Philosophy"] },
  { name: "Rachel Fernflores", departments: ["Philosophy"] },
  { name: "Jonathan Fernsler", departments: ["Physics"] },
  { name: "Gregg Fiegel", departments: ["Civil and Environmental Engineering"] },
  { name: "Jonathan Fischer", departments: ["Engineering Technology"] },
  { name: "Eric Fisher", departments: ["Economics"] },
  { name: "Carlos Flores", departments: ["Economics"] },
  { name: "Emily Fogle", departments: ["Chemistry and Biochemistry"] },
  { name: "Sophia Forster", departments: ["English"] },
  { name: "Samuel Frame", departments: ["Statistics"] },
  { name: "Clinton Francis", departments: ["Biological Sciences"] },
  { name: "Derik Frantz", departments: ["Chemistry and Biochemistry"] },
  { name: "Laura Freberg", departments: ["Psychology and Child Development"] },
  { name: "Tali Freed", departments: ["Industrial and Manufacturing Engineering"] },
  { name: "Daniel Frishberg", departments: ["Computer Science"] },
  { name: "Antonio Garcia", departments: ["Physics"] },
  { name: "Sean Gasiorek", departments: ["Mathematics"] },
  { name: "Hunter Glanz", departments: ["Statistics"] },
  { name: "Marni Goldenberg", departments: ["Experience Industry Management"] },
  { name: "Javier Gonzalez-Sanchez", departments: ["Computer Science"] },
  { name: "Anya Goodman", departments: ["Chemistry and Biochemistry"] },
  { name: "Brian Granger", departments: ["Physics"] },
  { name: "Todd Grundmeier", departments: ["Mathematics"] },
  { name: "Caixing Gu", departments: ["Mathematics"] },
  { name: "Thomas Gutierrez", departments: ["Physics"] },
  { name: "Matthew Haberland", departments: ["BioResource and Agricultural Engineering"] },
  { name: "Todd Hagobian", departments: ["Kinesiology and Public Health"] },
  { name: "Garrett Hall", departments: ["Civil and Environmental Engineering"] },
  { name: "Leslie Hamachi", departments: ["Chemistry and Biochemistry"] },
  { name: "Lynn Hamilton", departments: ["Agribusiness"] },
  { name: "Margaret Hamilton", departments: ["Mathematics"] },
  { name: "Stephen Hamilton", departments: ["Economics"] },
  { name: "James Hanson", departments: ["Civil and Environmental Engineering"] },
  { name: "Trevor Harding", departments: ["Materials Engineering"] },
  { name: "Kristin Hardy", departments: ["Biological Sciences"] },
  { name: "Michael Haungs", departments: ["Computer Science", "Liberal Arts and Engineering Studies"] },
  { name: "Benjamin Hawkins", departments: ["Biomedical Engineering"] },
  { name: "Scott Hazelwood", departments: ["Biomedical Engineering"] },
  { name: "Edward Himelblau", departments: ["Biological Sciences"] },
  { name: "Chance Hoellwarth", departments: ["School of Education", "Physics"] },
  { name: "Michael Holden", departments: ["Mechanical Engineering"] },
  { name: "Bret Holladay", departments: ["Statistics"] },
  { name: "Robert Holtzapple", departments: ["Physics"] },
  { name: "Matthew Hopper", departments: ["History"] },
  { name: "Marc Horney", departments: ["Animal Science"] },
  { name: "Patrick Howe", departments: ["Journalism"] },
  { name: "Daniel Howes", departments: ["BioResource and Agricultural Engineering"] },
  { name: "Borislov Hristov", departments: ["Computer Science"] },
  { name: "Silas Hsu", departments: ["Computer Science"] },
  { name: "Sean Hurley", departments: ["Agribusiness"] },
  { name: "Shelley Hurt", departments: ["Political Science"] },
  { name: "Juliana Huzzey", departments: ["Animal Science"] },
  { name: "Chad Immoos", departments: ["Chemistry and Biochemistry"] },
  { name: "Taiyo Inoue", departments: ["Mathematics"] },
  { name: "Elizabeth Jeffery", departments: ["Physics"] },
  { name: "Ryan Jenkins", departments: ["Philosophy"] },
  { name: "Xiaomin Jin", departments: ["Electrical Engineering"] },
  { name: "Jennifer Jipson", departments: ["Psychology and Child Development"] },
  { name: "Sanjiv Jaggia", departments: ["Economics"] },
  { name: "Jonathan James", departments: ["Economics"] },
  { name: "Daniel Jansen", departments: ["Civil and Environmental Engineering"] },
  { name: "John Jasbinsek", departments: ["Physics"] },
  { name: "Jessica Jensen", departments: ["School of Education"] },
  { name: "Nipoli Kamdar", departments: ["Economics"] },
  { name: "Iksoon Kang", departments: ["Animal Science"] },
  { name: "Eric Kantorowski", departments: ["Chemistry and Biochemistry"] },
  { name: "Ajay Kathuria", departments: ["Industrial Technology and Packaging"] },
  { name: "Thomas Katona", departments: ["Biomedical Engineering"] },
  { name: "Krista Kauffmann", departments: ["English"] },
  { name: "Anton Kaul", departments: ["Mathematics"] },
  { name: "Ayaan Kazerouni", departments: ["Computer Science"] },
  { name: "Sarah Keadle", departments: ["Kinesiology and Public Health"] },
  { name: "Andrew Kean", departments: ["Mechanical Engineering"] },
  { name: "Aaron Keen", departments: ["Computer Science"] },
  { name: "James Keese", departments: ["Social Sciences"] },
  { name: "Malcolm Keif", departments: ["Graphic Communication"] },
  { name: "Scott Kelting", departments: ["Construction Management"] },
  { name: "Brian Kennelly", departments: ["World Languages and Cultures"] },
  { name: "Foaad Khosmood", departments: ["Computer Science", "Computer Engineering"] },
  { name: "Jennifer Klay", departments: ["Physics"] },
  { name: "Andrew Kline", departments: ["Construction Management"] },
  { name: "Stephen Klisch", departments: ["Mechanical Engineering"] },
  { name: "Charles Knight", departments: ["Biological Sciences"] },
  { name: "Stacy Kolegraff", departments: ["Construction Management"] },
  { name: "Gita Kolluru", departments: ["Biological Sciences"] },
  { name: "Tatiana Kuriabova", departments: ["Physics"] },
  { name: "Sara Kuwahara", departments: ["BioResource and Agricultural Engineering"] },
  { name: "Lily Laiho", departments: ["Biomedical Engineering"] },
  { name: "Amy Lammert", departments: ["Food Science and Nutrition"] },
  { name: "Carrie Langner", departments: ["Psychology and Child Development"] },
  { name: "Michael Latner", departments: ["Political Science"] },
  { name: "Peter Laursen", departments: ["Architectural Engineering"] },
  { name: "John Lawson", departments: ["Architectural Engineering"] },
  { name: "Sean Lema", departments: ["Biological Sciences"] },
  { name: "Patrick Lemieux", departments: ["Mechanical Engineering"] },
  { name: "Jason Lepore", departments: ["Economics"] },
  { name: "Kevin Lertwachara", departments: ["Management, HR, and Information Systems"] },
  { name: "Tony Lewis", departments: ["Management, HR, and Information Systems"] },
  { name: "Albert Liddicoat", departments: ["Electrical Engineering"] },
  { name: "Jeffrey Liese", departments: ["Mathematics"] },
  { name: "Patrick Lin", departments: ["Philosophy"] },
  { name: "Joyce Lin", departments: ["Mathematics"] },
  { name: "Kevin Lin", departments: ["Experience Industry Management"] },
  { name: "Bo Liu", departments: ["BioResource and Agricultural Engineering"] },
  { name: "Heather Liwanag", departments: ["Biological Sciences"] },
  { name: "Molly Loberg", departments: ["History"] },
  { name: "Bryan Lohmar", departments: ["Agribusiness"] },
  { name: "Todd Long", departments: ["Philosophy"] },
  { name: "Susana Lopez", departments: ["Psychology and Child Development"] },
  { name: "Sara Lopus", departments: ["Social Sciences"] },
  { name: "Ulric Lund", departments: ["Statistics"] },
  { name: "Tryg Lundquist", departments: ["Civil and Environmental Engineering"] },
  { name: "Christopher Lupo", departments: ["Computer Science"] },
  { name: "Benjamin Lutz", departments: ["Mechanical Engineering"] },
  { name: "Ruoxi Ma", departments: ["Graphic Communication"] },
  { name: "Thomas Mackin", departments: ["Mechanical Engineering"] },
  { name: "Kenneth Macro", departments: ["Graphic Communication"] },
  { name: "Addison Maerz", departments: ["Management, HR, and Information Systems"] },
  { name: "Bwalya Malama", departments: ["Natural Resources Management and Environmental Sciences"] },
  { name: "Derek Manheim", departments: ["Civil and Environmental Engineering"] },
  { name: "Paul Marchbanks", departments: ["English"] },
  { name: "Silvia Marijuan", departments: ["World Languages and Cultures"] },
  { name: "Colleen Marlow", departments: ["Physics"] },
  { name: "David Marshall", departments: ["Aerospace Engineering"] },
  { name: "Andres Martinez", departments: ["Chemistry and Biochemistry"] },
  { name: "Nathaniel Martinez", departments: ["Biological Sciences"] },
  { name: "Tom Mase", departments: ["Mechanical Engineering"] },
  { name: "Themistoklis Mastoridis", departments: ["Physics"] },
  { name: "Hans Mayer", departments: ["Mechanical Engineering"] },
  { name: "Karen McGaughey", departments: ["Statistics"] },
  { name: "Timothy McHale", departments: ["Social Sciences"] },
  { name: "Alyson McLamore", departments: ["Music"] },
  { name: "Bryan Mealy", departments: ["Computer Engineering"] },
  { name: "Elsa Medina", departments: ["Mathematics"] },
  { name: "Eric Mehiel", departments: ["Aerospace Engineering"] },
  { name: "Joseph Mello", departments: ["Mechanical Engineering"] },
  { name: "Anthony Mendes", departments: ["Mathematics"] },
  { name: "Theresa Migler", departments: ["Computer Science"] },
  { name: "Matthew Moelter", departments: ["Physics"] },
  { name: "Robb Moss", departments: ["Civil and Environmental Engineering"] },
  { name: "Jennifer Mott", departments: ["Mechanical Engineering"] },
  { name: "Joydeep Mukherjee", departments: ["Computer Science"] },
  { name: "Sumona Mukhopadhyay", departments: ["Computer Science"] },
  { name: "Misgana Muleta", departments: ["Civil and Environmental Engineering"] },
  { name: "Karen Munoz-Christian", departments: ["World Languages and Cultures"] },
  { name: "William Murray", departments: ["Mechanical Engineering"] },
  { name: "Jasmine Nation", departments: ["Liberal Studies"] },
  { name: "Jenell Navarro", departments: ["Ethnic Studies"] },
  { name: "Jose Navarro", departments: ["Ethnic Studies"] },
  { name: "Payam Nayeri", departments: ["Electrical Engineering"] },
  { name: "Aydin Nazmi", departments: ["Food Science and Nutrition"] },
  { name: "Grace Neff", departments: ["Chemistry and Biochemistry"] },
  { name: "Dawn Neill", departments: ["Interdisciplinary Studies in the Liberal Arts"] },
  { name: "Stern Neill", departments: ["Marketing"] },
  { name: "Leslie Nelson", departments: ["Communication Studies"] },
  { name: "Phillip Nico", departments: ["Computer Science"] },
  { name: "Thomas Nordenholz", departments: ["Mechanical Engineering"] },
  { name: "Cornelius Nuworsoo", departments: ["City and Regional Planning"] },
  { name: "Christine O'Hara", departments: ["Landscape Architecture"] },
  { name: "Eric Ocegueda", departments: ["Mechanical Engineering"] },
  { name: "John Oliver", departments: ["Computer Engineering"] },
  { name: "Clare Olsen", departments: ["Architecture"] },
  { name: "Tomas Oppenheim", departments: ["Mechanical Engineering"] },
  { name: "Patrick Orson", departments: ["Mathematics"] },
  { name: "Joel Orth", departments: ["History"] },
  { name: "Brian Osborn", departments: ["Architecture"] },
  { name: "Rebekah Oulton", departments: ["Civil and Environmental Engineering"] },
  { name: "Nirupam Pal", departments: ["Civil and Environmental Engineering"] },
  { name: "H.H. Palandoken", departments: ["Chemistry and Biochemistry"] },
  { name: "Jianbiao Pan", departments: ["Industrial and Manufacturing Engineering"] },
  { name: "Anurag Pande", departments: ["Civil and Environmental Engineering"] },
  { name: "Maria Pantoja", departments: ["Computer Science"] },
  { name: "Dana Paquin", departments: ["Mathematics"] },
  { name: "Alexis Pasulka", departments: ["Biological Sciences"] },
  { name: "Pratish Patel", departments: ["Finance"] },
  { name: "Erin Pearse", departments: ["Mathematics"] },
  { name: "Zachary Peterson", departments: ["Computer Science"] },
  { name: "Steffen Peuker", departments: ["Mechanical Engineering"] },
  { name: "Suzanne Phelan", departments: ["Kinesiology and Public Health"] },
  { name: "Stephen Phillips", departments: ["Architecture"] },
  { name: "Wayne Pilkington", departments: ["Electrical Engineering"] },
  { name: "Kari Pilolla", departments: ["Food Science and Nutrition"] },
  { name: "Jason Poon", departments: ["Electrical Engineering"] },
  { name: "Hemanth Porumamila", departments: ["Mechanical Engineering"] },
  { name: "Majid Poshtan", departments: ["Electrical Engineering"] },
  { name: "Vladimir Prodanov", departments: ["Electrical Engineering"] },
  { name: "Elvira Pulitano", departments: ["Ethnic Studies"] },
  { name: "Eivis Qenani-Petrela", departments: ["Agribusiness"] },
  { name: "Bing Qu", departments: ["Civil and Environmental Engineering"] },
  { name: "Joseph Ragsdale", departments: ["Landscape Architecture"] },
  { name: "Ashraf Rahim", departments: ["Civil and Environmental Engineering"] },
  { name: "Shikha Rahman", departments: ["Civil and Environmental Engineering"] },
  { name: "Nishi Rajakaruna", departments: ["Biological Sciences"] },
  { name: "Cyrus Ramezani", departments: ["Finance"] },
  { name: "Mahdi Rastad", departments: ["Finance"] },
  { name: "Scott Reaves", departments: ["Food Science and Nutrition"] },
  { name: "Gordon Rees", departments: ["Natural Resources Management and Environmental Sciences"] },
  { name: "Zoe Rehnberg", departments: ["Statistics"] },
  { name: "Steven Rein", departments: ["Statistics"] },
  { name: "Dylan Retsek", departments: ["Mathematics"] },
  { name: "Benjamin Richert", departments: ["Mathematics"] },
  { name: "John Ridgely", departments: ["Mechanical Engineering"] },
  { name: "Kate Riley", departments: ["Mathematics"] },
  { name: "Laura Rios", departments: ["Physics"] },
  { name: "Matt Ritter", departments: ["Biological Sciences"] },
  { name: "Joni Roberts", departments: ["Kinesiology and Public Health"] },
  { name: "Emily Robinson", departments: ["Statistics"] },
  { name: "Briana Ronan", departments: ["School of Education"] },
  { name: "Xiaoying Rong", departments: ["Graphic Communication"] },
  { name: "Mira Rosenthal", departments: ["English"] },
  { name: "Kevin Ross", departments: ["Statistics"] },
  { name: "Soma Roy", departments: ["Statistics"] },
  { name: "Stacey Rucas", departments: ["Social Sciences"] },
  { name: "Trevor Ruiz", departments: ["Statistics"] },
  { name: "Steven Runyon", departments: ["Chemistry"] },
  { name: "Steven Ruszczycky", departments: ["English"] },
  { name: "Ben Ruttenberg", departments: ["Biological Sciences"] },
  { name: "Mugizi Rwebangira", departments: ["Computer Science"] },
  { name: "Anelise Sabbag", departments: ["Statistics"] },
  { name: "Mohammad Sadek", departments: ["BioResource and Agricultural Engineering"] },
  { name: "Edmond Saliklis", departments: ["Architectural Engineering"] },
  { name: "Fernando Sanchez", departments: ["World Languages and Cultures"] },
  { name: "Erik Sapper", departments: ["Chemistry and Biochemistry"] },
  { name: "Andrew Schaffner", departments: ["Statistics"] },
  { name: "Julia Schedler", departments: ["Statistics"] },
  { name: "Daniel Scheitrum", departments: ["Agribusiness"] },
  { name: "Amelie Schinck-Mikel", departments: ["Mathematics"] },
  { name: "Paul Schmitt", departments: ["Computer Science"] },
  { name: "Christiane Schroeter", departments: ["Agribusiness"] },
  { name: "Peter Schuster", departments: ["Mechanical Engineering"] },
  { name: "Keri Schwab", departments: ["Experience Industry Management"] },
  { name: "Debora Schwartz", departments: ["English"] },
  { name: "Peter Schwartz", departments: ["Physics"] },
  { name: "Gregory Schwartz", departments: ["BioResource and Agricultural Engineering"] },
  { name: "Gregory Scott", departments: ["Chemistry and Biochemistry"] },
  { name: "Brian Self", departments: ["Mechanical Engineering"] },
  { name: "John Seng", departments: ["Computer Science", "Computer Engineering"] },
  { name: "Ariel Setniker", departments: ["Mathematics"] },
  { name: "Aric Shafran", departments: ["Economics"] },
  { name: "Yan Shan", departments: ["Journalism"] },
  { name: "Jonathan Shapiro", departments: ["Mathematics"] },
  { name: "John Sharpe", departments: ["Physics"] },
  { name: "Morgan Sherman", departments: ["Mathematics"] },
  { name: "Joongmin Shin", departments: ["Industrial Technology and Packaging"] },
  { name: "Kim Shollenberger", departments: ["Mechanical Engineering"] },
  { name: "Angelos Sikalidis", departments: ["Food Science and Nutrition"] },
  { name: "Lonny Simonian", departments: ["Construction Management"] },
  { name: "Jagjit Singh", departments: ["Industrial Technology and Packaging"] },
  { name: "Devkishen Sisodia", departments: ["Computer Science"] },
  { name: "Seeta Sistla", departments: ["Natural Resources Management and Environmental Sciences"] },
  { name: "Jeffrey Sklar", departments: ["Statistics"] },
  { name: "Amy Skoll", departments: ["International Strategy and Security"] },
  { name: "Lynne Slivovsky", departments: ["Computer Engineering"] },
  { name: "Hugh Smith", departments: ["Computer Engineering"] },
  { name: "Taylor Smith", departments: ["Psychology and Child Development"] },
  { name: "Gabriel Soldatenko", departments: ["Ethnic Studies"] },
  { name: "Jacob Sparks", departments: ["Philosophy"] },
  { name: "Jill Speece", departments: ["Industrial and Manufacturing Engineering"] },
  { name: "Kim Sprayberry", departments: ["Animal Science"] },
  { name: "Lubomir Stanchev", departments: ["Computer Science"] },
  { name: "Taryn Stanko", departments: ["Management, HR, and Information Systems"] },
  { name: "Mark Stankus", departments: ["Mathematics"] },
  { name: "Sandra Stannard", departments: ["Architecture"] },
  { name: "Diana Stanton", departments: ["Theatre and Dance"] },
  { name: "Paul Stegner", departments: ["English"] },
  { name: "Scott Steinmaus", departments: ["Plant Sciences"] },
  { name: "Daniel Story", departments: ["Philosophy"] },
  { name: "Christy Strand", departments: ["Biological Sciences"] },
  { name: "Michael Strange", departments: ["Engineering Technology"] },
  { name: "Ciera Street", departments: ["Mathematics"] },
  { name: "Stuart Styles", departments: ["BioResource and Agricultural Engineering"] },
  { name: "Christopher Surfleet", departments: ["Natural Resources Management and Environmental Sciences"] },
  { name: "Benjamin Swan", departments: ["Agricultural Education and Communication"] },
  { name: "Lisa Sweatt", departments: ["Psychology and Child Development"] },
  { name: "Lawrence Sze", departments: ["Mathematics"] },
  { name: "Robert Szlavik", departments: ["Biomedical Engineering"] },
  { name: "Pasha Tabatabai", departments: ["Physics"] },
  { name: "Stefan Talke", departments: ["Civil and Environmental Engineering"] },
  { name: "Taufik", departments: ["Electrical Engineering"] },
  { name: "James Tejani", departments: ["History"] },
  { name: "Brady Teufel", departments: ["Journalism"] },
  { name: "Tracy Thatcher", departments: ["Civil and Environmental Engineering"] },
  { name: "Allison Theobold", departments: ["Statistics"] },
  { name: "Jafra Thomas", departments: ["Kinesiology and Public Health"] },
  { name: "John Thompson", departments: ["World Languages and Cultures"] },
  { name: "Glen Thorncroft", departments: ["Mechanical Engineering"] },
  { name: "Lars Tomanek", departments: ["Biological Sciences"] },
  { name: "Cesar Torres-Bustamente", departments: ["Landscape Architecture"] },
  { name: "Cynthia Trevisan", departments: ["Physics"] },
  { name: "Tom Trice", departments: ["History"] },
  { name: "Carmen Trudell", departments: ["Architecture"] },
  { name: "William Tsai", departments: ["Mechanical Engineering", "Engineering Technology"] },
  { name: "Marilyn Tseng", departments: ["Kinesiology and Public Health"] },
  { name: "Ashraf Tubeileh", departments: ["Plant Sciences"] },
  { name: "Ryan Tully-Doyle", departments: ["Mathematics"] },
  { name: "Colleen Twomey", departments: ["Graphic Communication"] },
  { name: "David Vagnoni", departments: ["Animal Science"] },
  { name: "MT Vallarta", departments: ["Ethnic Studies"] },
  { name: "Kathryn Vasilaky", departments: ["Economics"] },
  { name: "Dina Vees", departments: ["Graphic Communication"] },
  { name: "Alison Ventura", departments: ["Kinesiology and Public Health"] },
  { name: "Jonathan Ventura", departments: ["Computer Science"] },
  { name: "Priya Verma", departments: ["Natural Resources Management and Environmental Sciences"] },
  { name: "Francis Villablanca", departments: ["Biological Sciences"] },
  { name: "Stamatis Vokos", departments: ["Physics"] },
  { name: "Richard Volpe", departments: ["Agribusiness"] },
  { name: "Larisa Vredevoe", departments: ["Biological Sciences"] },
  { name: "Ryan Wade", departments: ["International Strategy and Security"] },
  { name: "Catherine Waitinas", departments: ["English"] },
  { name: "Daniel Waldorf", departments: ["Industrial and Manufacturing Engineering"] },
  { name: "John Walker", departments: ["Statistics"] },
  { name: "Robert Wallace", departments: ["Philosophy"] },
  { name: "Ryan Walter", departments: ["Physics"] },
  { name: "Xuan Wang", departments: ["Industrial and Manufacturing Engineering"] },
  { name: "Cindy Wang", departments: ["Marketing"] },
  { name: "Long Wang", departments: ["Civil and Environmental Engineering"] },
  { name: "Sandra Ward", departments: ["Chemistry and Biochemistry"] },
  { name: "David Watts", departments: ["Landscape Architecture"] },
  { name: "Katharine Watts", departments: ["Chemistry and Biochemistry"] },
  { name: "Paul Weber", departments: ["Construction Management"] },
  { name: "TJ Weber", departments: ["Marketing"] },
  { name: "Kimberly Westermann", departments: ["Accounting"] },
  { name: "Crow White", departments: ["Biological Sciences"] },
  { name: "Emily White", departments: ["Architecture"] },
  { name: "Michael Whitt", departments: ["Biomedical Engineering"] },
  { name: "Steven Wilkinson", departments: ["Chemistry and Biochemistry"] },
  { name: "Jean Williams", departments: ["Political Science"] },
  { name: "Nicholas Williams", departments: ["Natural Resources Management and Environmental Sciences"] },
  { name: "Jeffrey Wong", departments: ["Plant Sciences"] },
  { name: "Jeong Woo", departments: ["Construction Management"] },
  { name: "Zoe Wood", departments: ["Computer Science"] },
  { name: "Leah Wood", departments: ["School of Education"] },
  { name: "Christopher Woodruff", departments: ["Music"] },
  { name: "Ava Wright", departments: ["Philosophy"] },
  { name: "Jack Wroldsen", departments: ["Accounting"] },
  { name: "Xi Wu", departments: ["Mechanical Engineering"] },
  { name: "Siyuan Xing", departments: ["Mechanical Engineering"] },
  { name: "Hocheol Yang", departments: ["Graphic Communication"] },
  { name: "Grace Yeh", departments: ["Ethnic Studies"] },
  { name: "Alejandra Yep", departments: ["Biological Sciences"] },
  { name: "Marie Yeung", departments: ["Biological Sciences"] },
  { name: "Vincent Yeung", departments: ["Animal Science"] },
  { name: "Miranda Yin", departments: ["Marketing"] },
  { name: "Frank Yip", departments: ["Chemistry and Biochemistry"] },
  { name: "Jennifer Yost", departments: ["Biological Sciences"] },
  { name: "Helen Yu", departments: ["Electrical Engineering"] },
  { name: "Eduardo Zambrano", departments: ["Economics"] },
  { name: "Sarah Zeitler", departments: ["Chemistry and Biochemistry"] },
  { name: "Ning Zhang", departments: ["Political Science"] },
  { name: "Shanju Zhang", departments: ["Chemistry and Biochemistry"] },
  { name: "Jane Zhang", departments: ["Electrical Engineering"] },
  { name: "Chuancai Zhang", departments: ["Accounting"] },
  { name: "Pei Zhang", departments: ["Experience Industry Management"] },
  { name: "Alan Zhang", departments: ["Mechanical Engineering"] },
  { name: "David Zigler", departments: ["Chemistry and Biochemistry"] },
  { name: "Matthew Zoerb", departments: ["Chemistry and Biochemistry"] },
  { name: "David Zoller", departments: ["Philosophy"] },
];

/** Get faculty for a given department (case-insensitive partial match) */
export function getFacultyByDepartment(department: string): FacultyMember[] {
  const q = department.trim().toLowerCase();
  if (!q) return [];
  return CALPOLY_FACULTY.filter((f) =>
    f.departments.some((d) => d.toLowerCase().includes(q))
  ).sort((a, b) => a.name.localeCompare(b.name));
}
