export type DepartmentRecord = {
  code: string;
  name: string;
  aliases: string[];
};

const CALPOLY_DEPARTMENT_ALIASES: Readonly<Record<string, readonly string[]>> = {
  AERO: ["Aerospace Engineering"],
  AG: ["Agriculture", "College of Agriculture Food and Environmental Sciences"],
  AGB: ["Agribusiness", "Agricultural Business"],
  AGC: ["Agricultural Communication", "Agricultural Communications"],
  AGED: ["Agricultural Education"],
  ANT: ["Anthropology"],
  ARCE: ["Architectural Engineering"],
  ARCH: ["Architecture"],
  ART: ["Art", "Art and Design"],
  ASCI: ["Animal Science"],
  ASTR: ["Astronomy and Astrophysics", "Astronomy"],
  BIO: ["Biology", "Biological Sciences"],
  BMED: ["Biomedical Engineering"],
  BOT: ["Botany"],
  BRAE: ["BioResource and Agricultural Engineering", "Bioresource and Agricultural Engineering"],
  BUS: ["Business", "Orfalea College of Business"],
  CD: ["Child Development"],
  CE: ["Civil Engineering", "Civil and Environmental Engineering"],
  CEP: ["Cooperative Education"],
  CHE: ["Chemistry"],
  CHEM: ["Chemistry", "Chemistry and Biochemistry", "Biochemistry"],
  CHIN: ["Chinese"],
  CI: ["Curriculum and Instruction", "School of Education"],
  CM: ["Construction Management"],
  COM: ["Computers"],
  COMS: ["Communication Studies", "Communications"],
  CPE: ["Computer Engineering"],
  CRP: ["City and Regional Planning", "Urban Planning"],
  CRU: ["Cruise", "Marine Transportation"],
  CSC: ["Computer Science", "Computer Science and Software Engineering", "Comp Sci"],
  DANC: ["Dance", "Theatre and Dance"],
  DATA: ["Data Science"],
  DL: ["Deck Labs", "Marine Transportation"],
  DSCI: ["Dairy Science"],
  ECO: ["Economics"],
  ECON: ["Economics"],
  EDES: ["Environmental Design", "College of Architecture and Environmental Design"],
  EDUC: ["Education", "School of Education"],
  EE: ["Electrical Engineering"],
  EGL: ["English"],
  EIM: ["Experience Industry Management", "Hospitality"],
  ELAP: ["Educational Leadership and Administration Program"],
  EM: ["Emergency Management"],
  ENG: ["Engineering"],
  ENGL: ["English"],
  ENGR: ["Engineering", "General Engineering"],
  ENVE: ["Environmental Engineering", "Civil and Environmental Engineering"],
  EPO: ["Engineering Plant Operations"],
  ERSC: ["Earth Science", "Natural Resources Management and Environmental Sciences"],
  ES: ["Ethnic Studies"],
  ESCI: ["Environmental Sciences", "Natural Resources Management and Environmental Sciences"],
  ESM: ["Early Start Math", "Mathematics"],
  ET: ["Engineering Technology"],
  FDSC: ["Food Science"],
  FF: ["Firefighting"],
  FPE: ["Fire Protection Engineering"],
  FR: ["French"],
  FSN: ["Food Science and Nutrition", "Nutrition"],
  GEOG: ["Geography", "Social Sciences"],
  GEOL: ["Geology", "Physics"],
  GER: ["German"],
  GMA: ["Global Studies and Marine Affairs"],
  GOV: ["Government", "Political Science"],
  GRC: ["Graphic Communication"],
  GSB: ["Graduate Studies Business", "Business"],
  HCSA: ["Higher Education Counseling and Student Affairs"],
  HIST: ["History"],
  HLTH: ["Health", "Kinesiology and Public Health", "Public Health"],
  HNRC: ["Honors Program"],
  HNRS: ["Honors Program"],
  IBL: ["International Business", "Business"],
  IME: ["Industrial and Manufacturing Engineering"],
  ISLA: ["Interdisciplinary Studies in the Liberal Arts", "Humanities"],
  ITAL: ["Italian", "World Languages and Cultures"],
  ITP: ["Industrial Technology and Packaging", "Business"],
  JOUR: ["Journalism"],
  JPNS: ["Japanese", "World Languages and Cultures"],
  KINE: ["Kinesiology", "Kinesiology and Public Health"],
  LA: ["Landscape Architecture"],
  LAES: ["Liberal Arts and Engineering Studies"],
  LAN: ["Language", "World Languages and Cultures"],
  LAW: ["Law", "Political Science"],
  LDR: ["Leadership", "Military Science"],
  LS: ["Liberal Studies"],
  MATE: ["Materials Engineering"],
  MATH: ["Mathematics", "Math"],
  MCRO: ["Microbiology", "Biological Sciences"],
  ME: ["Mechanical Engineering"],
  MGT: ["Management", "Business"],
  MPM: ["Maritime Policy and Management", "Philosophy"],
  MSCI: ["Marine Science", "Biological Sciences"],
  MSL: ["Military Science Leadership", "Military Science"],
  MTH: ["Mathematics", "Math"],
  MU: ["Music"],
  NAU: ["Nautical Science", "Marine Transportation"],
  NR: ["Natural Resources", "Natural Resources Management and Environmental Sciences"],
  NSC: ["Naval Science"],
  NUTR: ["Nutrition", "Food Science and Nutrition"],
  OCN: ["Oceanography"],
  PE: ["Physical Education", "Kinesiology and Public Health"],
  PHIL: ["Philosophy"],
  PHY: ["Physics"],
  PHYS: ["Physics"],
  PLSC: ["Plant Sciences"],
  POLS: ["Political Science", "Politics"],
  PSC: ["Physical Science"],
  PSY: ["Psychology", "Psychology and Child Development"],
  RELS: ["Religious Studies"],
  RPTA: ["Recreation Parks and Tourism Administration", "Recreation Parks Tourism Administration"],
  SCM: ["Science and Mathematics"],
  SOC: ["Sociology", "Social Sciences"],
  SPAN: ["Spanish", "World Languages and Cultures"],
  SPED: ["Special Education", "School of Education"],
  SS: ["Soil Science"],
  STAT: ["Statistics", "Stats"],
  TEM: ["Transportation Engineering Management"],
  TH: ["Theatre", "Theater", "Theatre and Dance"],
  UNIV: ["University Studies"],
  WGQS: ["Women's Gender and Queer Studies", "Women Gender and Queer Studies"],
  WLC: ["World Languages and Cultures"],
  WVIT: ["Wine and Viticulture"],
  TEST: ["Test Department"],
  TBD: ["To Be Determined"],
};

export const CALPOLY_DEPARTMENTS: readonly DepartmentRecord[] = Object.entries(
  CALPOLY_DEPARTMENT_ALIASES
).map(([code, [name, ...aliases]]) => ({
  code,
  name,
  aliases,
}));

export const CALPOLY_DEPARTMENT_CODES = CALPOLY_DEPARTMENTS.map((department) => department.code);

export function getDepartmentByCode(code: string | null | undefined): DepartmentRecord | null {
  if (!code) return null;
  return CALPOLY_DEPARTMENTS.find((department) => department.code === code) ?? null;
}
